/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs1_ra174_2014_taskmanager_Statistics_JniStats */

#ifndef _Included_rtrk_pnrs1_ra174_2014_taskmanager_Statistics_JniStats
#define _Included_rtrk_pnrs1_ra174_2014_taskmanager_Statistics_JniStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs1_ra174_2014_taskmanager_Statistics_JniStats
 * Method:    calcStats
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_rtrk_pnrs1_ra174_12014_taskmanager_Statistics_JniStats_calcStats
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
